# Generated by Django 5.1 on 2024-09-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_image_post_title_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
