# Generated by Django 5.1 on 2024-09-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_image_post_imagen_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagen',
            new_name='image',
        ),
    ]
