# Generated by Django 5.1 on 2024-09-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_title'),
        ('posts', '0012_rename_imagen_post_image'),
    ]

    operations = [
    ]
