# Generated by Django 5.1 on 2024-09-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_merge_20240917_1959"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/posts_images/"
            ),
        ),
    ]
